const APP_ID = "solidcraft";

/* Precache contract — generated by the production build, never maintained by
   hand. `npm run build:sw` (scripts/generate-sw.js) rewrites the marked block
   below from the finished dist/ tree and writes the result to dist/sw.js, so
   CACHE_VERSION is a fingerprint of the precached bytes and ASSETS lists only
   URLs that actually exist in the deployed output.

   In the source tree the block is deliberately empty. dist/css/style.min.css,
   dist/js/theme-init.min.js and dist/js/script.min.js are produced by the
   build and do not exist beside these sources, so naming them here made
   cache.addAll() reject against the development server — atomically, leaving
   the whole precache empty and the worker unable to install. An empty list
   installs cleanly, so development gets a worker that activates and serves,
   with no precached shell to go stale against the files being edited.

   These two values are the only difference between the two trees; everything
   below is canonical runtime logic that ships unchanged. */
/* build:sw-manifest:start */
const CACHE_VERSION = "dev";

const ASSETS = [];
/* build:sw-manifest:end */

const CACHE_NAME = `${APP_ID}-v${CACHE_VERSION}`;
const IS_DEV = CACHE_VERSION === "dev";

const STATIC_DESTINATIONS = new Set([
  "style",
  "script",
  "font",
  "image",
  "manifest",
]);

const isCacheableResponse = (response) => response && response.ok;

const persistRuntimeResponse = (event, request, responsePromise) => {
  event.waitUntil(
    responsePromise.then(
      ({ response, fromNetwork }) => {
        if (!fromNetwork || !isCacheableResponse(response)) return;

        /* Clone here rather than inside the caches.open() callback. This
           handler is registered on responsePromise before the one
           event.respondWith() adds, so it runs first, while the body is still
           untouched. Past that asynchronous boundary the page already owns the
           response: clone() throws "Response body is already used" and the
           put() below is never reached. */
        const copy = response.clone();

        return caches
          .open(CACHE_NAME)
          .then((cache) => cache.put(request, copy));
      },
      () => undefined,
    ),
  );
};

/* Both lifecycle handlers pass event.waitUntil() one promise covering the
   cache work *and* the worker/client transition that follows it, so the
   browser is required to keep the event alive until that transition has
   settled — not only until the cache step has.

   Development still precaches nothing: the manifest block is empty there, so
   the install promise is the transition alone. */
self.addEventListener("install", (event) => {
  const precached = IS_DEV
    ? Promise.resolve()
    : caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS));

  event.waitUntil(precached.then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter(
              (key) =>
                key.startsWith(`${APP_ID}-v`) && (IS_DEV || key !== CACHE_NAME),
            )
            .map((key) => caches.delete(key)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  const url = new URL(req.url);
  const isSameOrigin = url.origin === self.location.origin;

  if (req.method !== "GET") return;
  if (!isSameOrigin) return;

  if (IS_DEV) {
    event.respondWith(fetch(req));
    return;
  }

  const isHTML =
    req.mode === "navigate" || req.headers.get("accept")?.includes("text/html");

  const isStaticAsset =
    STATIC_DESTINATIONS.has(req.destination) ||
    /\.(?:css|js|mjs|png|jpg|jpeg|gif|svg|webp|avif|ico|woff2?|ttf|otf|eot|webmanifest)$/i.test(
      url.pathname,
    );

  if (isHTML) {
    const responsePromise = fetch(req).then((response) => ({
      response,
      fromNetwork: true,
    }));

    persistRuntimeResponse(event, req, responsePromise);

    event.respondWith(
      responsePromise
        .then(({ response }) => response)
        .catch(() =>
          caches
            .match(req, { ignoreSearch: true })
            .then((cached) => cached || caches.match("/offline.html")),
        ),
    );

    return;
  }

  if (isStaticAsset) {
    const responsePromise = caches.match(req).then((cached) => {
      if (cached) {
        return {
          response: cached,
          fromNetwork: false,
        };
      }

      return fetch(req).then((response) => ({
        response,
        fromNetwork: true,
      }));
    });

    persistRuntimeResponse(event, req, responsePromise);

    event.respondWith(responsePromise.then(({ response }) => response));

    return;
  }

  event.respondWith(fetch(req));
});
